"""
==========================================================
DOCX Export

Generates a professional Microsoft Word report from the
🎵 Song Analytics Dashboard.

Version : 1.0
==========================================================
"""

from io import BytesIO

from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT

from src.report_generator import generate_report


def export_docx(df):
    """
    Generate Executive Report (.docx)
    """

    report = generate_report(df)

    document = Document()

    # ======================================================
    # Title
    # ======================================================

    title = document.add_heading(
        "United States Top 50 Playlist Performance\n"
        "& Song Popularity Trend Analysis",
        level=0
    )

    title.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

    subtitle = document.add_paragraph()

    subtitle.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

    subtitle.add_run(
        "Executive Historical Analytics Report"
    ).bold = True

    subtitle.add_run(
        f"\nGenerated: {report['generated_on']}"
    )

    subtitle.add_run(
        f"\nDashboard Version: {report['dashboard_version']}"
    )

    subtitle.add_run(
        f"\nAnalysis Type: {report['analysis_type']}"
    )

    # ======================================================
    # Executive Summary
    # ======================================================

    document.add_heading(
        "1. Executive Summary",
        level=1
    )

    document.add_paragraph(
        report["summary"]
    )

    # ======================================================
    # Dataset Metrics
    # ======================================================

    metrics = report["metrics"]

    document.add_heading(
        "2. Dataset Overview",
        level=1
    )

    table = document.add_table(
        rows=1,
        cols=2
    )

    table.style = "Light Grid Accent 1"

    hdr = table.rows[0].cells

    hdr[0].text = "Metric"

    hdr[1].text = "Value"

    rows = [

        ("Playlist Records",
         f"{metrics['total_records']:,}"),

        ("Unique Songs",
         f"{metrics['unique_songs']:,}"),

        ("Unique Artists",
         f"{metrics['unique_artists']:,}"),

        ("Average Popularity",
         f"{metrics['avg_popularity']:.1f}"),

        ("Explicit Songs",
         f"{metrics['explicit_pct']:.1f}%"),

        ("Best Playlist Rank",
         f"#{metrics['best_rank']}"),

        ("Top Artist",
         metrics["top_artist"]),

        ("Artist Share",
         f"{metrics['top_artist_share']:.1f}%"),

    ]

    for metric, value in rows:

        cells = table.add_row().cells

        cells[0].text = metric

        cells[1].text = str(value)

    # ======================================================
    # Insights
    # ======================================================

    document.add_heading(
        "3. Key Business Insights",
        level=1
    )

    for insight in report["insights"]:

        document.add_paragraph(
            insight,
            style="List Bullet"
        )

    # ======================================================
    # Conclusion
    # ======================================================

    document.add_heading(
        "4. Executive Conclusion",
        level=1
    )

    document.add_paragraph(
        report["conclusion"]
    )

    # ======================================================
    # Disclaimer
    # ======================================================

    document.add_heading(
        "5. Disclaimer",
        level=1
    )

    document.add_paragraph(
        "This report is automatically generated from the "
        "currently filtered historical playlist dataset. "
        "The dashboard provides descriptive analytics only "
        "and does not perform prediction, recommendation, "
        "or causal inference."
    )

    # ======================================================
    # Footer
    # ======================================================

    footer = document.add_paragraph()

    footer.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

    run = footer.add_run(
        "\nGenerated by 🎵 Song Analytics Dashboard\n"
        "© 2026 Kartikeya Mishra"
    )

    run.italic = True

    run.font.size = Pt(9)

    # ======================================================
    # Save
    # ======================================================

    file = BytesIO()

    document.save(file)

    file.seek(0)

    return file